resources:
  - url: /local/slider-entity-row.js?v=1
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module
  - url: /local/cards/lovelace-card-tools/card-tools.js?v=0.3
    type: js
  - url: /local/cards/lovelace-fold-entity-row/fold-entity-row.js?v=1.0
    type: js

title: Home
views:
########################################################
##
##              LIGHTS
##
########################################################
  - cards:
      - entities:
          - type: custom:slider-entity-row
            entity: light.all_kitchen_lights
            name: All
            icon: mdi:light-switch
          - entity: light.kitchen_light
            name: Main light
            icon: mdi:ceiling-light
          - entity: light.sonoff_kitchenlight
            name: Cooking area
            icon: mdi:track-light
          - type: custom:fold-entity-row
            head:
                entity: light.kitchen_spots
                name: Spots
                icon: mdi:track-light
            items:
              - entity: light.kitchen_spot_1
                name: Spot 1
                icon: mdi:track-light
              - entity: light.kitchen_spot_2
                name: Spot 2
                icon: mdi:track-light
              - entity: light.kitchen_spot_3
                name: Spot 3
                icon: mdi:track-light
        show_header_toggle: true
        title: Kitchen
        type: entities
      - entities:
          - type: custom:slider-entity-row
            entity: light.all_bedroom_lights
            name: All
            icon: mdi:light-switch
          - entity: light.eric_nightstand
            name: Nightstand
            icon: mdi:lamp
          - entity: light.eric_desk
            name: Desk
            icon: mdi:desk-lamp
          - entity: light.floor_light
            name: Floor lamp
            icon: mdi:floor-lamp
          - entity: light.livingroom
            name: Shelf lamp
            icon: mdi:lamp
        show_header_toggle: true
        title: Bedroom
        type: entities
      - entities:
          - entity: light.nick_room_main
            name: Main light
            icon: mdi:ceiling-light
        show_header_toggle: false
        title: Nick Room
        type: entities
      - entities:
          - entity: light.sonoff_livingroom_light
            name: Lamp
            icon: mdi:lamp
          - entity: light.sonoff_bedroom_light
            name: Spot
            icon: mdi:ceiling-light
        show_header_toggle: true
        title: Livingroom
        type: entities
    icon: 'mdi:lightbulb'
    title: Lights
  ########################################################
  ##
  ##              HOME
  ##
  ########################################################
  - cards:
      - type: entity-filter
        entities:
          - device_tracker.ericiphone
          - device_tracker.nickiphone
          - device_tracker.nathalieiphone
          - device_tracker.iphonedemina
        state_filter:
          - home
        card:
          type: glance
          title: People at home
      # - type: custom:mini-graph-card
      #   entities:
      #     - entity: sensor.temperature_158d0002789d06
      #       name: Bedroom
      #     - entity: sensor.temperature_158d0002789e17
      #       name: Kitchen
      #   name: Temperature
      - type: glance
        title: Doors and windows
        entities:
        - entity: sensor.front_door
          name: Front door
        - entity: sensor.window_1
          name: Kitchen
        - entity: sensor.window_3
          name: Bedroom
        - entity: sensor.window_2
          name: Dummy
      - type: glance
        title: Sensors
        entities:
        - entity: sensor.water_1
          name: Washing machine
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.temperature_158d0002789d06
            line_color: '#3498db'
            line_width: 8
            font_size: 75
            name: Bedroom
          - type: custom:mini-graph-card
            entities:
              - sensor.humidity_158d0002789d06
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
            name: Bedroom
          - type: custom:mini-graph-card
            entities:
              - sensor.pressure_158d0002789d06
            line_color: '#f1c40f'
            line_width: 8
            name: Bedroom
            icon: mdi:gauge
            font_size: 75
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.temperature_158d0002789e17
            line_color: '#3498db'
            line_width: 8
            font_size: 75
            name: Kitchen
          - type: custom:mini-graph-card
            entities:
              - sensor.humidity_158d0002789e17
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
            name: Kitchen
          - type: custom:mini-graph-card
            entities:
              - sensor.pressure_158d0002789e17
            line_color: '#f1c40f'
            line_width: 8
            name: Kitchen
            icon: mdi:gauge
            font_size: 75
    icon: 'mdi:home'
    title: Home

########################################################
##
##              WEATHER
##
########################################################
  - badges: []
    cards:
      - entities:
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_daily_temperature_low
          - sensor.dark_sky_daily_temperature_high
          - sensor.air_pressure_template
          - sensor.dark_sky_uv_index
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_precip_type_template
          - sensor.dark_sky_precip_probability_template
          - sensor.dark_sky_daily_precip_intensity_max
          - sensor.dark_sky_wind_bearing_template
          - sensor.dark_sky_wind_speed
        show_header_toggle: true
        title: Today's Forecast
        type: entities
      - entities:
          - sensor.dark_sky_daily_low_temperature_1
          - sensor.dark_sky_daily_high_temperature_1
          - sensor.air_pressure_tomorrow_template
          - sensor.dark_sky_cloud_coverage_1
          - sensor.dark_sky_precip_type_tomorrow_template
          - sensor.dark_sky_precip_probability_tomorrow_template
          - sensor.dark_sky_daily_max_precip_intensity_1
          - sensor.dark_sky_wind_bearing_tomorrow_template
          - sensor.dark_sky_wind_speed_1
        show_header_toggle: true
        title: Tomorrow's Forecast
        type: entities
      - entities:
          - sensor.day_night
          - sensor.solar_angle
          - sensor.sunrise
          - sensor.sunset
          - sensor.moon
          - sensor.season_template
        show_header_toggle: true
        title: Sun & Moon
        type: entities
    icon: 'mdi:weather-partlycloudy'
    path: weather
    title: Weather
########################################################
##
##              SYSTEM
##
########################################################
  - cards:
      - type: vertical-stack
        cards:
          - entities:
              - sensor.time_online
              - sensor.connected_clients
              - sensor.current_version
              - sensor.last_boot
            show_header_toggle: false
            title: General
            type: entities
          - entities:
              - sensor.network_in
              - sensor.network_out
              - sensor.packets_in
              - sensor.packets_out
            show_header_toggle: false
            title: Network
            type: entities
      - type: vertical-stack
        cards:
          - type: gauge
            unit: '%'
            entity: sensor.processor_use
            name: Processor usage
            severity:
              green: 0
              yellow: 45
              red: 85
          - type: gauge
            unit: '%'
            entity: sensor.memory_use_percent
            name: Memory usage
            severity:
              green: 0
              yellow: 45
              red: 85
          - type: gauge
            unit: '%'
            entity: sensor.disk_use_percent
            name: Disk usage
            severity:
              green: 0
              yellow: 45
              red: 85
          - type: gauge
            unit: '%'
            entity: sensor.swap_use_percent
            name: Swap usage
            severity:
              green: 0
              yellow: 45
              red: 85
      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.load_1m_template
            name: Load 1m
            max: 1.0
            severity:
              green: 0.0
              yellow: 0.5
              red: 0.9
          - type: gauge
            entity: sensor.load_5m_template
            name: Load 5m
            max: 1.0
            severity:
              green: 0.0
              yellow: 0.5
              red: 0.9
          - type: gauge
            entity: sensor.load_15m_template
            name: Load 15m
            max: 1.0
            severity:
              green: 0.0
              yellow: 0.5
              red: 0.9
    icon: 'mdi:server'
    title: System

########################################################
##
##              AUTOMATIONS
##
########################################################
  - cards:
      - type: markdown
        content: >
          ## System Settings

          Panel for system settings. If you are not supposed to be here, please do not change anything.

          **Any changes will be reported to the administrator.**
      - entities:
          - automation.sunset
          - automation.coming_home_lights
          - automation.bathroom_light_on
          - automation.bathroom_light_off
          - automation.bathroom_light_on_switch
          - automation.bathroom_light_off_switch
          - automation.toggle_liviginroom_light
          - automation.toggle_bedroom_lights
          - automation.toggle_nick_room_light
          - automation.toggle_kitchen_lights
          - script.test_telegr
        show_header_toggle: true
        title: Automation
        type: entities
      - entities:
          - switch.flux_bedroom
          - switch.flux_kitchen
          - switch.flux_nick_room
        show_header_toggle: true
        title: Switches
        type: entities
      - entities:
          - binary_sensor.water_leak_sensor_158d000237265a
        show_header_toggle: true
        title: Developments
        type: entities
      - entities:
          - sensor.front_door
          - sensor.window_1
          - sensor.window_2
          - sensor.window_3
        show_header_toggle: true
        title: Sensors
        type: entities
    icon: 'mdi:settings'
    title: Automation
