resources:
  - url: /local/slider-entity-row.js?v=1
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module

title: Home
views:
########################################################
##
##              LIGHTS
##
########################################################
  - cards:
      - entities:
          - type: custom:slider-entity-row
            entity: light.all_kitchen_lights
            name: All
            icon: mdi:light-switch
          - entity: light.kitchen_light
            name: Main light
            icon: mdi:ceiling-light
          - entity: light.sonoff_kitchenlight
            name: Cooking area
            icon: mdi:track-light
          - entity: light.kitchen_spots
            name: Spots
            icon: mdi:track-light
        show_header_toggle: true
        title: Kitchen
        type: entities
      - entities:
          - entity: light.eric_nightstand
            name: Nightstand
            icon: mdi:lamp
          - entity: light.eric_desk
            name: Desk
            icon: mdi:desk-lamp
          - entity: light.floor_light
            name: Floor lamp
            icon: mdi:floor-lamp
          - entity: light.sonoff_bedroom_light
            name: Spot
            icon: mdi:lamp
          - entity: light.livingroom
            name: Shelf lamp
            icon: mdi:lamp
        show_header_toggle: true
        title: Bedroom
        type: entities
      - entities:
          - entity: light.nick_room_main
            name: Main light
            icon: mdi:ceiling-light
        show_header_toggle: true
        title: Nick Room
        type: entities
      - entities:
          - entity: light.sonoff_livingroom_light
            name: Lamp
            icon: mdi:lamp
        show_header_toggle: true
        title: Livingroom
        type: entities
    icon: 'mdi:lightbulb'
    title: Lights
  ########################################################
  ##
  ##              HOME
  ##
  ########################################################
  - cards:
      - type: entity-filter
        entities:
          - device_tracker.ericiphone
          - device_tracker.nickiphone
          - device_tracker.nathalieiphone
          - device_tracker.iphonedemina
        state_filter:
          - home
        card:
          type: glance
          title: People at home
      # - type: custom:mini-graph-card
      #   entities:
      #     - entity: sensor.temperature_158d0002789d06
      #       name: Bedroom
      #     - entity: sensor.temperature_158d0002789e17
      #       name: Kitchen
      #   name: Temperature
      - type: glance
        title: Doors and windows
        entities:
        - entity: sensor.front_door
          name: Front door
        - entity: sensor.window_1
          name: Kitchen
        - entity: sensor.window_3
          name: Bedroom
        - entity: sensor.window_2
          name: Dummy
      - type: glance
        title: Sensors
        entities:
        - entity: sensor.water_1
          name: Washing machine
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.temperature_158d0002789d06
            line_color: '#3498db'
            line_width: 8
            font_size: 75
            name: Bedroom
          - type: custom:mini-graph-card
            entities:
              - sensor.humidity_158d0002789d06
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
            name: Bedroom
          - type: custom:mini-graph-card
            entities:
              - sensor.pressure_158d0002789d06
            line_color: '#f1c40f'
            line_width: 8
            name: Bedroom
            icon: mdi:gauge
            font_size: 75
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.temperature_158d0002789e17
            line_color: '#3498db'
            line_width: 8
            font_size: 75
            name: Kitchen
          - type: custom:mini-graph-card
            entities:
              - sensor.humidity_158d0002789e17
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
            name: Kitchen
          - type: custom:mini-graph-card
            entities:
              - sensor.pressure_158d0002789e17
            line_color: '#f1c40f'
            line_width: 8
            name: Kitchen
            icon: mdi:gauge
            font_size: 75
    icon: 'mdi:home'
    title: Home
########################################################
##
##              AUTOMATIONS
##
########################################################
  - cards:
      - entities:
          - automation.sunset
          - automation.coming_home_lights
          - automation.bathroom_light_on
          - automation.bathroom_light_off
          - automation.bathroom_light_on_switch
          - automation.bathroom_light_off_switch
          - automation.toggle_liviginroom_light
          - automation.toggle_bedroom_lights
          - automation.toggle_nick_room_light
          - automation.toggle_kitchen_lights
          - script.test_telegr
        show_header_toggle: true
        title: Automation
        type: entities
      - entities:
          - switch.flux_bedroom
          - switch.flux_kitchen
          - switch.flux_nick_room
        show_header_toggle: true
        title: Switches
        type: entities
      - entities:
          - binary_sensor.water_leak_sensor_158d000237265a
        show_header_toggle: true
        title: Developments
        type: entities
      - entities:
          - sensor.front_door
          - sensor.window_1
          - sensor.window_2
          - sensor.window_3
        show_header_toggle: true
        title: Sensors
        type: entities
    icon: 'mdi:settings'
    path: automation_view
    title: Automation
########################################################
##
##              WEATHER
##
########################################################
  - badges: []
    cards:
      - entities:
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_daily_temperature_low
          - sensor.dark_sky_daily_temperature_high
          - sensor.air_pressure_template
          - sensor.dark_sky_uv_index
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_precip_type_template
          - sensor.dark_sky_precip_probability_template
          - sensor.dark_sky_daily_precip_intensity_max
          - sensor.dark_sky_wind_bearing_template
          - sensor.dark_sky_wind_speed
        show_header_toggle: true
        title: Today's Forecast
        type: entities
      - entities:
          - sensor.dark_sky_daily_low_temperature_1
          - sensor.dark_sky_daily_high_temperature_1
          - sensor.air_pressure_tomorrow_template
          - sensor.dark_sky_cloud_coverage_1
          - sensor.dark_sky_precip_type_tomorrow_template
          - sensor.dark_sky_precip_probability_tomorrow_template
          - sensor.dark_sky_daily_max_precip_intensity_1
          - sensor.dark_sky_wind_bearing_tomorrow_template
          - sensor.dark_sky_wind_speed_1
        show_header_toggle: true
        title: Tomorrow's Forecast
        type: entities
      - entities:
          - sensor.day_night
          - sensor.solar_angle
          - sensor.sunrise
          - sensor.sunset
          - sensor.moon
          - sensor.season_template
        show_header_toggle: true
        title: Sun & Moon
        type: entities
    icon: 'mdi:weather-partlycloudy'
    path: weather
    title: Weather
  - badges: []
    cards:
      - entities:
          - sensor.time_online
          - sensor.connected_clients
          - sensor.current_version
          - sensor.disk_free_space
          - sensor.memory_use
        show_header_toggle: true
        title: System Status
        type: entities
    icon: 'mdi:server'
    path: system_view
    title: System
  - badges: []
    cards:
      - entity: media_player.etv
        type: media-control
    icon: 'mdi:television-classic'
    path: media_view
    title: Media
