###########################################
# System Sensors
###########################################
- platform: uptime
  name: Time Online

- platform: systemmonitor
  resources:
    # - type: since_last_boot
    # - type: memory_use_percent
    - type: memory_use

- platform: command_line
  command: "df -h | grep none | awk '{print $4}'"
  name: "Disk Free Space"
  scan_interval: 60

- platform: api_streams

- platform: version

#Since last boot is gone ... :-(
# - platform: template
#   sensors:
#     since_last_boot_template:
#       friendly_name: Time since last boot
#       value_template: >-
#         {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
#         {%- set count = slb | length -%}
#         {%- set hms = slb[count - 1] -%}
#         {%- set hms_trimmed = hms.split('.')[0] -%}
#         {%- set hms_split = hms_trimmed.split(':') -%}
#         {%- set hours = hms_split[0] | int -%}
#
#         {%- if count == 3 -%}
#           {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
#         {%- endif -%}
#         {%- if hours > 0 -%}
#           {%- if hours == 1 -%}
#             1 hour
#           {%- else -%}
#             {{ hours }} hours
#           {%- endif -%}
#         {%- endif -%}
