- platform: template
  sensors:
    front_door:
      friendly_name: "Front door"
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001b7a868', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d0001b7a868', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_1:
      friendly_name: "Window Kitchen"
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d00020455e1', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d00020455e1', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_2:
      friendly_name: "window_2"
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d00020456e9', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d00020456e9', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    window_3:
      friendly_name: "Window Bedroom"
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000205b57f', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000205b57f', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
    water_1:
      friendly_name: "Water sensor"
      value_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000205b57f', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.door_window_sensor_158d000205b57f', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
