- alias: coming_home_lights
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001b7a868
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: sun
        after: sunset
        after_offset: "-0:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.kitchen
