- alias: toggle_liviginroom_light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_158d0001834217
      click_type: single
  action:
    service_template: >
      {% if is_state('group.livingroom', 'on') %}
        homeassistant.turn_off
      {% else %}
        homeassistant.turn_on
      {% endif %}
    entity_id: group.livingroom
