- alias: toggle_nick_room_light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002135ae2
      click_type: single
  action:
    service_template: >
      {% if is_state('group.nick_room', 'on') %}
        homeassistant.turn_off
      {% else %}
        homeassistant.turn_on
      {% endif %}
    entity_id: group.nick_room
