#https://home-assistant.io/components/device_tracker/

####################################################
#                                                  #
#           DEVICE TRACKER - FRITZBOX              #
#                                                  #
####################################################

#https://www.home-assistant.io/components/device_tracker.fritz/

- platform: fritz
  host: 192.168.178.1
  # username: !secret fritz_devicetracker_username
  # password: !secret fritz_devicetracker_password
  interval_seconds: 15
  consider_home: 180
  track_new_devices: yes

####################################################
#                                                  #
#              DEVICE TRACKER - NMAP               #
#                                                  #
####################################################

#https://home-assistant.io/components/device_tracker.nmap_tracker/

# - platform: nmap_tracker
#   hosts: 192.168.178.1-255
#   home_interval: 3

####################################################
#                                                  #
#           DEVICE TRACKER - BLUETOOTH             #
#                                                  #
####################################################

# https://www.home-assistant.io/integrations/bluetooth_tracker/

# - platform: bluetooth_tracker
